.PHONY: install
install:
	@cd react && bun install
	@cd svelte && bun install
	@cd vue && bun install

.PHONY: build
build:
	@cd react && bun run build
	@cd svelte && bun run build
	@cd vue && bun run build